spring:
  application:
    name: microservice-gateway-zuul
security:
  basic:
    enabled: true   #添加eureka的登录认证
  user:
    name: user
    password: password123
server:
  port: 8740
eureka:
  client:
   register-with-eureka: true
   fetch-registry: true
   service-url:
      defaultZone: http://user:password123@localhost:8761/eureka  #此种形式的认证为linux的系统下的curl Style 认证方式
  instance:
    prefer-ip-address: true   #显示status的ip
    status-page-url: http://localhost:${server.port}/swagger-ui.html # ${server.port}为该服务的端口号  / 开启swagger2
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 5000
zuul:
  host:
    socket-timeout-millis: 60000  
    connect-timeout-millis: 60000
  routes:
    bcd:
      path: /user/**
      service-id: microservice-provider-user

hystrix:  
  command:  
    default:  
      execution:  
        isolation:  
          thread:  
            timeoutInMilliseconds: 60000  
            
ribbon:
   ReadTimeout: 60000  
   ConnectTimeout: 60000 
   eureka:
    enabled: false
     
microservice-provider-user:     # 这边是ribbon要请求的微服务的serviceId
  ribbon:
    listOfServers: http://localhost:7800,http://localhost:7801